config/routes.rb
Rails.application.routes.draw do
  get '/about/index', to: 'about#index'
  
  root 'books#index'

  resources :books
  resources :categories
  resources :authors
  resources :publishers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
    validates :first_name, presence: true, length: {minimum:3, maximum:18}
    validates :last_name, presence: true, uniqueness: true, length: {minimum:3, maximum:18}
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  belongs_to :category
  belongs_to :author
  validates :title, presence: true, uniqueness: true, length: {minimum:3, maximum:25}
  validates :isbn, presence: true
  validates :year, presence: true
  validates :price, presence: true
  validates :buy, presence: true
  validates :excerpt, presence: true
  has_attached_file :image,
    :storage => :cloudinary,
    :path => ':class/:id/:style/:filename'
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates :image_file_name, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books, dependent: :destroy
    validates :name, presence: true, uniqueness: true, length: {minimum:3}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :books, dependent: :destroy
    validates :name, presence: true, uniqueness: true, length: {minimum:3}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About Us'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Author Created!"
      redirect_to root_path
    else
      if Author.exists?(last_name: @author.last_name)
        flash[:alert] = "Already exists!"
      elsif Author.where(first_name: @author.first_name).empty?
        flash[:alert] = "Please put your First Name"
      elsif Author.where(last_name: @author.last_name).empty?
        flash[:alert] = "Please put your Last Name"
      else
        flash[:alert] = "Oops! Something went wrong!"
      end
      render 'new'
    end
  end

  def edit
    @author = Author.find(
    params[:id]
    )
  end

  def update
    @author = Author.find(
    params[:id]
    )
    @author.update(author_params)
    flash[:notice] = "Writer's name updated"
    redirect_to author_path(@author)
  end

  def destroy
    @author = Author.find(
    params[:id]
    )
    @author.destroy
    flash[:notice] = "Writer deleted!"
    redirect_to authors_path
  end

  def index
    @page_title = 'Writers'
    @authors = Author.all.order(id: :desc)
  end

  def show
    @author = Author.find(
    params[:id]
    )
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @page_title = 'Add Book'
    @book = Book.new
    @categories = Category.all.order(id: :asc)
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Your book has been created"
      redirect_to book_path(@book)
    else
      flash[:alert] = "Oops! Something went wrong!"
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
      flash[:notice] = "Your book has been updated"
      redirect_to book_path(@book)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book deleted!"
    redirect_to books_path
  end

  def index
    @books = Book.all.order(id: :desc)
    @categories = Category.all.order(id: :asc)
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all.order(id: :asc)
  end

  private

  def book_params
    params.require(:book).permit(:title, :isbn, :year, :price, :buy, :excerpt, :format, :pages, :category_id, :author_id, :publisher_id, :image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category Created!"
      redirect_to root_path
    else
      if Category.exists?(name: @category.name)
        flash[:alert] = "Already exists!"
      elsif Category.where(name: @category.name).empty?
        flash[:alert] = "Name your category"
      else
        flash[:alert] = "Oops! Something went wrong!"
      end
      render 'new'
    end
  end

  def edit
    @category = Category.find(
    params[:id]
    )
  end

  def update
    @category = Category.find(
    params[:id]
    )
    @category.update(category_params)
    flash[:notice] = "Category has been updated!"
    redirect_to category_path(@category)
  end

  def destroy
    @category = Category.find(
    params[:id]
    )
    @category.destroy
    flash[:notice] = "Category deleted!"
    redirect_to categories_path
  end

  def index
    @page_title = 'Categories'
    @categories = Category.all.order(id: :desc)
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Publisher Created!"
      redirect_to root_path
    else
      if Publisher.exists?(name: @publisher.name)
        flash[:alert] = "Already exists!"
      elsif Publisher.where(name: @publisher.name).empty?
        flash[:alert] = "Name your Publisher"
      else
        flash[:alert] = "Oops! Something went wrong!"
      end
      render 'new'
    end
  end

  def edit
    @publisher = Publisher.find(
    params[:id]
    )
  end

  def update
    @publisher = Publisher.find(
    params[:id]
    )
    @publisher.update(publisher_params)
    flash[:notice] = "Publisher has been updated!"
    redirect_to publisher_path(@publisher)
  end

  def destroy
    @publisher = Publisher.find(
    params[:id]
    )
    @publisher.destroy
    flash[:notice] = "Publisher deleted!"
    redirect_to publishers_path
  end

  def index
    @page_title = 'Publishers'
    @publishers = Publisher.all.order(id: :desc)
  end

  def show
    @publisher = Publisher.find(
    params[:id]
    )
  end

  private

  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Update <small><%= @author.first_name + ' ' + @author.last_name %></small></h1>

<%= form_for (@author) do |f| %>
    <div class="form-group">
        <%= f.label :first_name, "First Name" %><br />
        <%= f.text_field :first_name, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :last_name, "Last Name" %><br />
        <%= f.text_field :last_name, class: "form-control" %><br />
    </div>

    <%= f.submit "Create Author", class:"btn btn-primary" %>
    <%= link_to  "Cancel", authors_path, class:"btn btn-danger" %>
<% end %>

app/views/authors/index.html.erb
<% if Author.all.empty? %>
    <p>There's no writers yet, go ahead and add one!</p><br /><br />
<% end %>
<div class="container mx-4 mb-5">
    <%= link_to  "Add new Writer", new_author_path, class: "btn btn-success h-25" %>
</div>
<% @authors.each do |c| %>
    <ul class="index-list">
        <li class="index-item">
            <%= link_to c.first_name + ' ' + c.last_name, author_path(c), class: "list-group-item bg-dark h-25 w-25" %>
            <p class="m-0 lead py-2"><%= c.books.count %> books</p>
            <%= link_to  "Add new Book", new_book_path, class: "btn btn-primary" %>
            <%= link_to  "Delete", author_path(c), method: :delete, data: { confirm: 'This will delete all books related to this author. Are you sure?' }, class: "btn btn-danger" %>
        </li>
    </ul>
<% end %>

app/views/authors/new.html.erb
<h2>Add New Author</h2>

<%= form_for (@author) do |f| %>
    <div class="form-group">
        <%= f.label :first_name, "First Name" %><br />
        <%= f.text_field :first_name, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :last_name, "Last Name" %><br />
        <%= f.text_field :last_name, class: "form-control" %><br />
    </div>

    <%= f.submit "Create Author", class:"btn btn-primary" %>
    <%= link_to  "Cancel", authors_path, class:"btn btn-danger" %>
<% end %>

app/views/authors/show.html.erb
<h1><%=@author.first_name + ' ' + @author.last_name%></h1>
<%= link_to  "Update Author", edit_author_path, class: "btn btn-primary mb-3" %>
<div id="books-index">
    <div class="row">
        <% if @author.books.empty? %>
            <div class="py-3 col-12">
                <p>This author has no books yet!</p>
                <%= link_to  "Add a Book", new_book_path, class: "btn btn-success" %>
            </div>
        <% else %>
            <div class="col-12">
                <%= link_to  "Add another Book", new_book_path, class: "btn btn-success" %>
            </div>
            <% @author.books.each do |book| %>
                <div class="py-3 col-md-4 col-sm-3">
                    <h4><%= book.title %></h4>
                    <%= image_tag book.image.url, class: "w-100 h-75" %>
                    <div class="d-flex">
                        <%= link_to  "Read More", book_path(book), class: "btn btn-primary w-75 mt-2 mr-1" %>
                        <%= link_to  "Delete", book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger w-25 mt-2 px-1" %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Update <small><%= @book.title %></small></h1>

<%= form_for (@book) do |f| %>
    <div class="form-group">
        <%= f.label :title, "Book Name" %><br />
        <%= f.text_field :title, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :isbn, "ISBN" %><br />
        <%= f.text_field :isbn, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :category, "Select Category" %><br />
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:"form-control"%><br /><br />
    </div>

    <div class="form-group">
        <%= f.label :author, "Author" %><br />
        <%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select One'}, class:"form-control"%><br /><br />
    </div>

    <div class="form-group">
        <%= f.label :publisher, "Publisher" %><br />
        <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:"form-control"%><br /><br />
    </div>

    <div class="form-group">
        <%= f.label :year, "Year" %><br />
        <%= f.number_field :year, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :format, "Format" %><br />
        <%= f.text_field :format, class: "form-control" %><br />
    </div>
    
    <div class="form-group">
        <%= f.label :excerpt, "Excerpt" %><br />
        <%= f.text_area :excerpt, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :pages, "Pages" %><br />
        <%= f.number_field :pages, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :price, "Price" %><br />
        <%= f.text_field :price, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :buy, "Buy" %><br />
        <%= f.text_field :buy, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :image, "Upload book image" %><br />
        <%= f.file_field :image %>
    </div>

    <%= f.submit "Update", class: "btn btn-primary" %>
    <%= link_to  "Cancel", root_path, class: "btn btn-danger" %>
<% end %>

app/views/books/index.html.erb
<div id="books-index">
    <% if Book.all.empty? %>
        <p>There's no books yet, go ahead and add few!</p><br /><br />
        <%= link_to  "Add new Book", new_book_path, class: "btn btn-primary" %>
    <% end %>
    <div class="row">
    <% @books.each do |book| %>
        <div class="py-3 col-md-4 col-sm-3">
            <h4><%= book.title %></h4>
            <%= image_tag book.image.url, class: "w-100 h-75" %>
            <div class="d-flex">
                <%= link_to  "Read More", book_path(book), class: "btn btn-primary w-75 mt-2 mr-1" %>
                <%= link_to  "Delete", book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger w-25 mt-2 px-1" %>
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/books/new.html.erb
<h1>Add New Book</h1>

<%= form_for (@book) do |f| %>
    <div class="form-group">
        <%= f.label :title, "Book Name" %><br />
        <%= f.text_field :title, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :isbn, "ISBN" %><br />
        <%= f.text_field :isbn, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :category, "Select Category" %><br />
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:"form-control"%><br /><br />
    </div>

    <div class="form-group">
        <%= f.label :author, "Author" %><br />
        <%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select One'}, class:"form-control"%><br /><br />
    </div>

    <div class="form-group">
        <%= f.label :publisher, "Publisher" %><br />
        <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:"form-control"%><br /><br />
    </div>

    <div class="form-group">
        <%= f.label :year, "Year" %><br />
        <%= f.number_field :year, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :format, "Format" %><br />
        <%= f.text_field :format, class: "form-control" %><br />
    </div>
    
    <div class="form-group">
        <%= f.label :excerpt, "Excerpt" %><br />
        <%= f.text_area :excerpt, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :pages, "Pages" %><br />
        <%= f.number_field :pages, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :price, "Price" %><br />
        <%= f.text_field :price, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :buy, "Buy" %><br />
        <%= f.text_field :buy, class: "form-control" %><br />
    </div>

    <div class="form-group">
        <%= f.label :image, "Upload book image" %><br />
        <%= f.file_field :image %>
    </div>

    <%= f.submit "Create Book", class: "btn btn-primary" %>
    <%= link_to  "Cancel", root_path, class: "btn btn-danger" %>
<% end %>

app/views/books/show.html.erb
<div id="books-show">
    <h2><%=@book.title%></h2>
    <div class="books-show-left">
        <%= image_tag @book.image.url, class: "w-100 pr-5" %>
    </div>
    <div class="books-show-right">
        <h3>Book info:</h3>
        <ul>
            <li><strong>Category: </strong><%=@book.category.name%></li>
            <li><strong>Author: </strong><%=@book.author.first_name + ' ' + @book.author.last_name%></li>
            <li><strong>Publisher: </strong><%=@book.publisher.name%></li>
            <li><strong>Year: </strong><%=@book.year%></li>
            <li><strong>ISBN: </strong><%=@book.isbn%></li>
            <li><strong>Format: </strong><%=@book.format%></li>
            <li><strong>Pages: </strong><%=@book.pages%></li>
        </ul>
        <%= link_to  "Buy $$", '#', class: "btn btn-success my-5" %>
    </div>
    <div class="clearfix">
        <h4>Excerpt</h4>
        <p><%=@book.excerpt%></p>
    </div>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<% if Category.all.empty? %>
    <p>There's no categories yet, go ahead and add few!</p><br /><br />
<% end %>
<div class="container mx-4 mb-5">
    <%= link_to  "Add new Category", new_category_path, class: "btn btn-success h-25" %>
</div>
<% @categories.each do |c| %>
    <ul class="index-list">
        <li class="index-item">
            <%= link_to c.name, category_path(c), class: "list-group-item bg-dark h-25 w-25" %>
            <p class="m-0 lead py-2"><%= c.books.count %> books</p>
            <%= link_to  "Add new book to this category", new_book_path, class: "btn btn-primary" %>
            <%= link_to  "Delete", category_path(c), method: :delete, data: { confirm: 'This will delete all books related to this category. Are you sure?' }, class: "btn btn-danger" %>
        </li>
    </ul>
<% end %>

app/views/categories/show.html.erb
<h1><%=@category.name%></h1>
<%= link_to  "Update Category", edit_category_path, class: "btn btn-primary mb-3" %>

<div id="books-index">
    <div class="row">
        <% if @category.books.empty? %>
            <div class="py-3 col-12">
                <p>This category has no books yet!</p>
                <%= link_to  "Add One", new_book_path, class: "btn btn-success" %>
            </div>
        <% else %>
            <div class="col-12">
                <%= link_to  "Add another Book", new_book_path, class: "btn btn-success" %>
            </div>
            <% @category.books.each do |book| %>
                <div class="py-3 col-md-4 col-sm-3">
                    <h4><%= book.title %></h4>
                    <%= image_tag book.image.url, class: "w-100 h-75" %>
                    <div class="d-flex">
                        <%= link_to  "Read More", book_path(book), class: "btn btn-primary w-75 mt-2 mr-1" %>
                        <%= link_to  "Delete", book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger w-25 mt-2 px-1" %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <nav class="nav nav-masthead justify-content-center">
            <li class="nav-link <%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to  "Home", root_path %></li>
            <li class="nav-link <%= params[:controller] == 'authors' ? 'active' : '' %>"><%= link_to "Our Writers", authors_path %></li>
            <li class="nav-link <%= params[:controller] == 'publishers' ? 'active' : '' %>"><%= link_to "Our Publishers", publishers_path %></li>
            <li class="nav-link <%= params[:controller] == 'categories' ? 'active' : '' %>"><%= link_to "Our Categories", categories_path %></li>
            <li class="nav-link <%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to  "About Us", about_index_path %></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add new</a>
              <ul class="dropdown-menu bg-dark p-3" aria-labelledby="navbarDropdown" role="menu">
                <li><%= link_to  "Book", new_book_path, class: "nav-link" %></li>
                <li><%= link_to  "Category", new_category_path, class: "nav-link" %></li>
                <li><%= link_to  "Author", new_author_path, class: "nav-link" %></li>
                <li><%= link_to  "Publisher", new_publisher_path, class: "nav-link" %></li>
              </ul>
            </li>
          </nav>
        </div>
      </header>
    </div>
    <div class="container">
      <h1>The Bookstore <small><%= @page_title ? @page_title : 'Welcome' %></small></h1>
    </div>
    <section class="py-4">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice] %></div>  
            <% end %>
            <% if flash[:alert] %>
              <div class="alert alert-danger"><%= flash[:alert] %></div>
            <% end %>
            <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render './partials/sidebar' %>
          </div>
        </div>
      </div>
    </section>

    <footer>
      <div class="container">
        <p>Copyright &copy; 2020.bksh-js. All rights reserved</p>
      </div>
    </footer>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<%if params[:controller] == 'about'%>
<div class="well">
	<h3>Location Info</h3>
	<ul>
		<li>The BookStore</li>
		<li>15, st.leave-me-alone, Alex, Egypt</li>
		<li>P.C: 22511</li>
		<li>Phone: +20 1146 467 077</li>
		<li>Email: bksh@bksh.com</li>
	</ul>
</div>
<% end %>

<% if params[:controller] == 'books' %>
<% if Category.all.empty? %>
	<p>No categories yet, go add some</p>
    <%= link_to  "Add new Category", new_category_path, class: "btn btn-success mt-5" %>
<% else %>
<div class="list-group">
	<% Category.all.each do |category| %>
		<%if Category.all.count <= 20 %>
			<%= link_to category.name, category_path(category), class: "list-group-item bg-dark" %>
		<% end %>
	<% end %>
	<% if Category.all.count >= 20 %>
		<% array = Category.all.take(20) %>
		<% array.each do |c| %>
			<%= link_to c.name, category_path(c), class: "list-group-item bg-dark" %>
		<% end %>
	<% end %>
	<% if Category.all.count >= 20 %>
		<%= link_to  "See More", categories_path, class: "btn btn-outline bg-white" %>
	<% end %>
</div>
<% end %>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/index.html.erb
<% if Publisher.all.empty? %>
    <p>There's no publishers yet, go ahead and add few!</p><br /><br />
<% end %>
<div class="container mx-4 mb-5">
    <%= link_to  "Add new Publisher", new_publisher_path, class: "btn btn-success h-25" %>
</div>
<% @publishers.each do |c| %>
    <ul class="index-list">
        <li class="index-item">
            <%= link_to c.name, publisher_path(c), class: "list-group-item bg-dark h-25 w-25" %>
            <p class="m-0 lead py-2"><%= c.books.count %> books</p>
            <%= link_to  "Add new book to this publisher", new_book_path, class: "btn btn-primary" %>
            <%= link_to  "Delete", publisher_path(c), method: :delete, data: { confirm: 'This will delete all books related to this publisher. Are you sure?' }, class: "btn btn-danger" %>
        </li>
    </ul>
<% end %>

app/views/publishers/show.html.erb
<h1><%=@publisher.name%></h1>
<%= link_to  "Update Publisher", edit_publisher_path, class: "btn btn-primary mb-3" %>
<div id="books-index">
    <div class="row">
        <% if @publisher.books.empty? %>
            <div class="py-3 col-12">
                <p>This publisher has no books yet!</p>
                <%= link_to  "Add One", new_book_path, class: "btn btn-success" %>
            </div>
        <% else %>
            <div class="col-12">
                <%= link_to  "Add another Book", new_book_path, class: "btn btn-success" %>
            </div>
            <% @publisher.books.each do |book| %>
                <div class="py-3 col-md-4 col-sm-3">
                    <h4><%= book.title %></h4>
                    <%= image_tag book.image.url, class: "w-100 h-75" %>
                    <div class="d-flex">
                        <%= link_to  "Read More", book_path(book), class: "btn btn-primary w-75 mt-2 mr-1" %>
                        <%= link_to  "Delete", book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger w-25 mt-2 px-1" %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>